---
- name: Deploy sshd root login config from controller with backup
  hosts: all
  become: yes
  gather_facts: false

  vars:
    sshd_dropin_file: /etc/ssh/sshd_config.d/01-permitrootlogin.conf
    local_config_file: /root/ansible/files/01-permitrootlogin.conf

  tasks:
    - name: Get today date
      ansible.builtin.set_fact:
        today: "{{ lookup('pipe', 'date +%Y%m%d') }}"

    - name: Backup existing sshd config if exists
      ansible.builtin.stat:
        path: "{{ sshd_dropin_file }}"
      register: sshd_conf_stat

    - name: Create backup with date
      ansible.builtin.command: >
        mv {{ sshd_dropin_file }}
        {{ sshd_dropin_file }}.bak.{{ today }}
      when: sshd_conf_stat.stat.exists

    - name: Copy new sshd config from controller
      ansible.builtin.copy:
        src: "{{ local_config_file }}"
        dest: "{{ sshd_dropin_file }}"
        owner: root
        group: root
        mode: '0600'
      notify: Restart sshd

    - name: Validate sshd configuration
      ansible.builtin.command: sshd -t
      changed_when: false

  handlers:
    - name: Restart sshd
      ansible.builtin.service:
        name: sshd
        state: restarted

