---
- name: Restrict root SSH login with Match Address
  hosts: all
  become: yes

  vars:
    sshd_dropin_file: /etc/ssh/sshd_config.d/01-permitrootlogin.conf
    trusted_ip: 192.168.243.249

  tasks:
    - name: Create sshd drop-in config for root access control
      ansible.builtin.copy:
        dest: "{{ sshd_dropin_file }}"
        owner: root
        group: root
        mode: '0600'
        content: |
          # {{ sshd_dropin_file }}
          # Restrict root login to specific server(s)

          # First match: Allow from trusted server
          Match Address {{ trusted_ip }}
              PermitRootLogin yes

          # Second match: Deny from everywhere else
          Match all
              PermitRootLogin no
      notify: Restart sshd

    - name: Validate sshd configuration
      ansible.builtin.command: sshd -t
      changed_when: false

  handlers:
    - name: Restart sshd
      ansible.builtin.service:
        name: sshd
        state: restarted

