---

- name: Probing Modules
  hosts: webservers
  tasks:
    - name: list files and directories
      shell:
        cmd: ls
        chdir: /home/
      register: files
    - name: show the files
      debug:
        var: files.stdout
